services:
  catcam:
    container_name: catcam
    build: .
    ports:
      - 5000:5000/udp # Incoming MPEG-TS stream from Pi
      - 8087:8080/tcp # Web interface
    volumes:
      - ./data:/data # Persistent detection log
      - ./cat_classifier.pt:/app/cat_classifier.pt
      - "./cat images:/app/cat images"
      - ./discord_feedback:/app/discord_feedback 
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN:-}
      - PRE_ROLL=5
      - POST_ROLL=5
      - HWACCEL=cpu
      - INFER_EVERY=3
      - CONF_THRESH=0.15
      - OMP_NUM_THREADS=2
      - MKL_NUM_THREADS=2
      - INFER_DEVICE=GPU
    restart: unless-stopped
networks: {}